version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  add_worker:
    build: ./arithmetic-system
    command: python -m app.workers.add_worker
    depends_on:
      - rabbitmq
      - redis

  sub_worker:
    build: ./arithmetic-system
    command: python -m app.workers.sub_worker
    depends_on:
      - rabbitmq
      - redis

  mul_worker:
    build: ./arithmetic-system
    command: python -m app.workers.mul_worker
    depends_on:
      - rabbitmq
      - redis

  div_worker:
    build: ./arithmetic-system
    command: python -m app.workers.div_worker
    depends_on:
      - rabbitmq
      - redis

  xsum_worker:
    build: ./arithmetic-system
    command: python -m app.workers.xsum_worker
    depends_on:
      - rabbitmq
      - redis

  xprod_worker:
    build: ./arithmetic-system
    command: python -m app.workers.xprod_worker
    depends_on:
      - rabbitmq
      - redis

  entrypoint:
    build: ./arithmetic-system
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
